#!/usr/bin/env python3

import os
import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")
    username=sys.argv[1].strip("@")
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    last_tweets=helpers.get_user_timeline(username, 50)
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    for tweet in last_tweets:
    # analyze word
        score = analyzer.analyze(tweet)
        if score > 0.0:
            sys.stdout.write(colored(score, "green"))
            print(" ", end='')
            print(colored(tweet, "green"))
        elif score < 0.0:
            sys.stdout.write(colored(score, "red")) 
            print(" ", end='')
            print(colored(tweet, "red"))
        else:
            sys.stdout.write(colored(score, "" "yellow"))
            print(" ", end='')
            print(colored(tweet, "yellow"))
            
        

if __name__ == "__main__":
    main()
